### ISSUE TITLE
Disappearing points

### ISSUE THREAD

**Issue by FieseKante** [freetimecoder/unreal-pcg-examples#1]
Hey,

as soon as I try to move the PCG actors the points disappear. The graphs seem to work, no errors. But it won't output any data?

**Comment by freetimecoder** [comment]
Unreal doesn't save the debug toggle on graph nodes. When the graph is regenerated without any node being debugged it does not generate any visual data. The graph still runs, but it doesn't look like it.

To solve this open the graph and enable debug on a node. Then it should work again ✨
